include ../../config.mk

CFLAGS += -I. -I$(INCLUDE_DIR)

C_FILES := osbclose.c \
	osbdcb.c \
	osbopen.c \
	oscheck.c \
	osdclose.c \
	osddcb.c \
	osdopen.c \
	osdread.c \
	osdwrite.c \
	osread.c \
	oswrite.c \
	osxcalc.c \
	osxclose.c \
	osxdcb.c \
	osxopen.c \
	osxread.c \
	osxwrite.c \
	rdjfcb.c \
	trkcalc.c

A_FILES :=

include ../../rules.mk
