[project]
name = "crent370"
version = "1.0.9-dev"
type = "library"

[build]
cflags = ["-Isrc/thdmgr", "-Isrc/time64"]

[build.sources]
c_dirs = [
  "src/clib",
  "src/cmtt",
  "src/crypto",
  "src/dyn75",
  "src/jes",
  "src/os",
  "src/racf",
  "src/smf",
  "src/thdmgr",
  "src/time64",
]
asm_dirs = ["asm"]

[mvs.build.datasets.punch]
suffix = "OBJECT"
dsorg = "PO"
recfm = "FB"
lrecl = 80
blksize = 19040
space = ["TRK", 600, 100, 200]

[mvs.build.datasets.ncalib]
suffix = "NCALIB"
dsorg = "PO"
recfm = "U"
lrecl = 0
blksize = 19069
space = ["TRK", 700, 100, 250]

[mvs.build.datasets.source]
suffix = "SOURCE"
dsorg = "PO"
recfm = "FB"
lrecl = 80
blksize = 19040
space = ["TRK", 600, 100, 200]

[mvs.build.datasets.maclib]
suffix = "MACLIB"
dsorg = "PO"
recfm = "FB"
lrecl = 80
blksize = 19040
space = ["TRK", 30, 10, 50]
local_dir = "maclib/"

[system]
maclibs = ["SYS1.HASPSRC"]
