include ../config.mk

C_FILES :=
A_FILES := @@aclose.asm \
	@@aline.asm \
	@@anote.asm \
	@@aopen.asm \
	@@apoint.asm \
	@@aread.asm \
	@@atrout.asm \
	@@awrite.asm \
	@@crt0.asm \
	@@crt1.asm \
	@@crtm.asm \
	@@crtsvc.asm \
	@@dynal.asm \
	@@exita.asm \
	@@freem.asm \
	@@getclk.asm \
	@@getm.asm \
	@@getpfx.asm \
	@@gettz.asm \
	gettzoff.asm \
	@@idcams.asm \
	@@longj.asm \
	@@ppaget.asm \
	@@setj.asm \
	@@ssctbn.asm \
	@@svc99.asm \
	@@system.asm

include ../rules.mk
