include ../../config.mk

CFLAGS += -I. -I$(INCLUDE_DIR)

C_FILES := jescanj.c \
	jesclose.c \
	jesdelj.c \
	jesiropn.c \
	jesirput.c \
	jesircls.c \
	jesjob.c \
	jesjobf1.c \
	jesjobfr.c \
	jesopen.c \
	jesprint.c \
	jesreque.c \
	jesxdone.c \
	jesxwrtr.c \
	josjobfr.c

A_FILES :=

include ../../rules.mk
