include ../../config.mk

CFLAGS += -I. -I$(INCLUDE_DIR)

C_FILES := \
	@@75.c \
	@@75acce.c \
	@@75bind.c \
	@@75clos.c \
	@@75conn.c \
	@@75exit.c \
	@@75gabn.c \
	@@75ghba.c \
	@@75ghbn.c \
	@@75init.c \
	@@75ioct.c \
	@@75list.c \
	@@75pnam.c \
	@@75recv.c \
	@@75sele.c \
	@@75selx.c \
	@@75send.c \
	@@75snam.c \
	@@75sock.c \
	@@75vect.c \
	asc2ebc.c \
	ebc2asc.c

A_FILES :=

include ../../rules.mk
