include ../../config.mk

CFLAGS += -I. -I$(INCLUDE_DIR)

C_FILES := @@cminit.c \
	@@cmqadd.c \
	@@cmqdel.c \
	@@cmterm.c \
	@@cmwadd.c \
	@@cmwdel.c \
	@@cmwshu.c \
	@@cmwwat.c

A_FILES :=

include ../../rules.mk
